module NatureBoy.Bufs where

import Data.Tuple (Tuple(..))

bufs :: Array (Tuple String String)
bufs =
  [ Tuple "low-g#" "https://freesound.org/data/previews/195/195285_3623377-hq.mp3"
  -- impros
  , Tuple "flute" "https://media.graphcms.com/eiKfSNIbSaiomCZQzXGA"
  -- siren
  , Tuple "siren" "https://freesound.org/data/previews/534/534550_11837619-hq.mp3"
  -- revcym
  , Tuple "revcym" " https://freesound.org/data/previews/240/240712_3552082-hq.mp3"
  -- drumz
          , Tuple "kick" "https://freesound.org/data/previews/189/189174_3296371-hq.mp3"

  , Tuple "slow-drum-pattern" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/stonerRock.mp3"
  , Tuple "drumz-cat-55" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/drumz-catCrabs55.ogg"
  , Tuple "drumz-cat-80" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/drumz-catCrabs80.ogg"
  , Tuple "drumz-cat-100" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/drumz-catCrabs100.ogg"
  , Tuple "drumz-cat-110" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/drumz-catCrabs110.ogg"
  , Tuple "drumz-cat-160" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/drumz-catCrabs160.ogg"
  -- gamelan
  , Tuple "kettle-g-sharp-3" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/kettleGSharp3.ogg"
  , Tuple "kettle-a-3" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/kettleA3.ogg"
  , Tuple "kettle-c-4" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/kettleC4.ogg"
  , Tuple "kettle-e-flat-4" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/kettleEFlat4.ogg"
  , Tuple "kettle-f-sharp-4" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/kettleFSharp4.ogg"
  -- impulses
  , Tuple "matrix-verb-3" "https://klank-share.s3-eu-west-1.amazonaws.com/in-a-sentimental-mood/Samples/Impulses/matrix-reverb3.wav"
  , Tuple "matrix-verb-3" "https://klank-share.s3-eu-west-1.amazonaws.com/in-a-sentimental-mood/Samples/Impulses/matrix-reverb3.wav"
  , Tuple "matrix-verb-5" "https://klank-share.s3-eu-west-1.amazonaws.com/in-a-sentimental-mood/Samples/Impulses/matrix-reverb5.wav"
  -- harmonic stuff
  ------- interj
  , Tuple "g-sharp-a-sharp-high" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/gSharpASharpInterjection.ogg"
  , Tuple "c-sharp-d-sharp-high" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/cSharpDSharpInterjection.ogg"
  , Tuple "g-a-high" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/gAInterjection.ogg"
  --------------- low d
  , Tuple "bassoon-low-d" "https://freesound.org/data/previews/154/154331_2626346-hq.mp3"
  , Tuple "low-guitar-d" "https://freesound.org/data/previews/117/117675_646701-hq.mp3"
  , Tuple "skiddaw-low-d" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/skiddawLowD.ogg"
  --------------- harm
  , Tuple "harm-0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/cSharpMinorPad.ogg"
  , Tuple "harm-0-120" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/cSharpMinorPad120.ogg"
  , Tuple "harm-0-110" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/cSharpMinorPad110.ogg"
  , Tuple "harm-0-90" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/cSharpMinorPad90.ogg"
  , Tuple "harm-0-70" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/cSharpMinorPad70.ogg"
  , Tuple "harm-0-40" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/cSharpMinorPad40.ogg"
  , Tuple "harm-1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/fSharpDiadPad.ogg"
  , Tuple "harm-1-120" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/fSharpDiadPad120.ogg"
  , Tuple "harm-1-50" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/fSharpDiadPad50.ogg"
  , Tuple "harm-1-90" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/fSharpDiadPad90.ogg"
  , Tuple "harm-2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/cSharpDSharpDiadPad100.ogg"
  , Tuple "pre-a-little-shy" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/preALittleShy.ogg"
  , Tuple "a-little-shy" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/aLittleShy.ogg"
  , Tuple "and-sad-of-eye" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andSadOfEye.ogg"
  , Tuple "but-very-wise-was" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/butVeryWiseWas.ogg"
  , Tuple "he" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/he.ogg"
  -- bass
  , Tuple "nasty-bass" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/nastyBass.ogg"
  -- snare
  , Tuple "snare-hit" "https://freesound.org/data/previews/100/100393_377011-hq.mp3"
  -- foghorns
  -- low, grave
  -- , Tuple "distant-low-blast" "https://freesound.org/data/previews/500/500146_401348-hq.mp3"
  -- nasty, clippy, beautiful
  -- , Tuple "nasty-rich-low" "https://freesound.org/data/previews/234/234681_1708550-hq.mp3"
  -- bold, straight
  -- , Tuple "bold-straight-pvc" "https://freesound.org/data/previews/507/507472_2977885-hq.mp3"
  -- single low-ish blast
  -- , Tuple "single-clear-blast" "https://freesound.org/data/previews/81/81874_1285056-hq.mp3"
  -- higher
  -- , Tuple "higher-fog-horn" "https://freesound.org/data/previews/92/92911_37876-hq.mp3"
  --------------------------------
  -- harmonic rising, glitchy
  -- , Tuple "rising-harm" "https://freesound.org/data/previews/430/430865_45576-hq.mp3"
  -- , Tuple "sitar" "https://freesound.org/data/previews/37/37715_347704-hq.mp3"
  ----------- pads
  -- , Tuple "twisty-pad" "https://freesound.org/data/previews/33/33183_250881-hq.mp3"
  --, Tuple "evolving" "https://freesound.org/data/previews/484/484850_16058-hq.mp3"
  -- yesHe
  , Tuple "warble" "https://freesound.org/data/previews/110/110212_1751865-hq.mp3"
  -- yesHe
  , Tuple "to-the-heavens" "https://freesound.org/data/previews/110/110211_1751865-hq.mp3"
  --, Tuple "low-energized" "https://freesound.org/data/previews/33/33182_250881-hq.mp3"
  --, Tuple "ethereal" "https://freesound.org/data/previews/352/352944_6523136-hq.mp3"
  ------------------------- THIS IS OUR BASS SOUND
  ------------------------- FOR THE SECOND PART
  , Tuple "bassplz" "https://freesound.org/data/previews/119/119059_181941-hq.mp3"
  , Tuple "scratchy-swell" "https://freesound.org/data/previews/417/417416_1453392-hq.mp3"
  --, Tuple "low-deep" "https://freesound.org/data/previews/350/350660_1676145-hq.mp3"
  --, Tuple "knock-pad" "https://freesound.org/data/previews/7/7402_1629-hq.mp3"
  --, Tuple "gnarly-feedback" "https://freesound.org/data/previews/213/213906_862453-hq.mp3"
  --, Tuple "low-drone" "https://freesound.org/data/previews/353/353549_6493436-hq.mp3"
  -- yesHe
  , Tuple "shaky-scratchy" "https://freesound.org/data/previews/277/277172_93137-hq.mp3"
  , Tuple "flag-banging" "https://freesound.org/data/previews/169/169798_1661766-hq.mp3"
  -- Ambiance
  --, Tuple "costal-ambiance" "https://freesound.org/data/previews/207/207553_285997-hq.mp3"
  --, Tuple "beautiful-birds" "https://freesound.org/data/previews/528/528661_1576553-hq.mp3"
  --, Tuple "robin" "https://freesound.org/data/previews/416/416529_5121236-hq.mp3"
  ------------- shredders
  -- second half good... nice and gear-y
  --, Tuple "indoor-shredder" "https://freesound.org/data/previews/82/82435_1276308-hq.mp3"
  --, Tuple "high-shrill-terrifying-shredder" "https://freesound.org/data/previews/181/181143_3374466-hq.mp3"
  --, Tuple "mechanical-clicking-shredder" "https://freesound.org/data/previews/78/78521_1218676-hq.mp3"
  --, Tuple "single-shred" "https://freesound.org/data/previews/26/26389_186469-hq.mp3"
  , Tuple "nice-high-shred" "https://freesound.org/data/previews/21/21755_29541-hq.mp3"
  -------------------- egg timer
  --, Tuple "egg-timer-wind-plus-ring" "https://freesound.org/data/previews/14/14263_31076-hq.mp3"
  , Tuple "egg-timer-ticking" "https://freesound.org/data/previews/468/468081_2247456-hq.mp3"
  ------------------ gamelan
  --, Tuple "gamelan-bali" "https://freesound.org/data/previews/257/257625_3932570-hq.mp3"
  , Tuple "low-c#-cello-drone" "https://freesound.org/data/previews/195/195278_3623377-hq.mp3"
  --, Tuple "handbell-c#" "https://freesound.org/data/previews/339/339808_5121236-hq.mp3"
  --, Tuple "guitar-8th-c#" "https://freesound.org/data/previews/372/372386_5968459-hq.mp3"
  --, Tuple "accordion-c#-aug" "https://freesound.org/data/previews/120/120692_649468-hq.mp3"
  --, Tuple "spoooooky-amb" "https://freesound.org/data/previews/277/277572_5338846-hq.mp3"
  -- rate 1.09 gets to C#
  --, Tuple "scary-c" "https://freesound.org/data/previews/277/277637_5338846-hq.mp3"
  -- , Tuple "gong-g-sharp" "https://media.graphcms.com/LFgrdeImQICudFzE1ShR"
  , Tuple "gong-g-sharp-reversed" "https://media.graphcms.com/pYrQiqMAT62OoVYQugg4"
  --, Tuple "power-chord-c-sharp" "https://freesound.org/data/previews/49/49275_177850-hq.mp3"
  --, Tuple "bassoon-c-sharp" "https://freesound.org/data/previews/154/154330_2626346-hq.mp3"
  --, Tuple "loud-awful-scream" "https://freesound.org/data/previews/267/267395_5004228-hq.mp3"
  --, Tuple "real-human-scream" "https://freesound.org/data/previews/536/536486_11937282-hq.mp3"
  --, Tuple "flute-c-sharp" "https://freesound.org/data/previews/154/154208_2626346-hq.mp3"
  --, Tuple "pipe-c-sharp" "https://freesound.org/data/previews/345/345192_5622625-hq.mp3"
  -- , Tuple "guitar-c-sharp" "https://freesound.org/data/previews/153/153957_2626346-hq.mp3"
  , Tuple "bass-c-sharp" "https://media.graphcms.com/0gp37YI7Q5mczsjAUiUH"
  --, Tuple "pizz-c-sharp" "https://freesound.org/data/previews/153/153642_2626346-hq.mp3"
  --, Tuple "pizz-e" "https://freesound.org/data/previews/153/153633_2626346-hq.mp3"
  --, Tuple "pizz-g-sharp" "https://freesound.org/data/previews/153/153637_2626346-hq.mp3"
  --, Tuple "bass-pizz-c-sharp" "https://freesound.org/data/previews/153/153805_2626346-hq.mp3"
  --, Tuple "guitar-high-c-sharp" "https://freesound.org/data/previews/153/153944_2626346-hq.mp3"
  --, Tuple "voice-like-c-sharp" "https://freesound.org/data/previews/315/315850_4557960-hq.mp3"
  , Tuple "terrifying-air-raid-siren" "https://freesound.org/data/previews/271/271132_5004228-hq.mp3"
  --, Tuple "shruti-box" "https://media.graphcms.com/qwlr3QDKQHmrLjD9smOY"
  , Tuple "chimez-above-c-sharp-drone" "https://media.graphcms.com/3Z0DXRxRtOTymo51DGev"
  , Tuple "middle-g-sharp-guitar" "https://freesound.org/data/previews/154/154013_2626346-hq.mp3"
  , Tuple "high-g-sharp-guitar" "https://freesound.org/data/previews/153/153984_2626346-hq.mp3"
  , Tuple "e-guitar" "https://freesound.org/data/previews/153/153980_2626346-hq.mp3"
  , Tuple "beautiful-birds" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/birds.ogg"
  , Tuple "plane-landing" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/planeLanding.ogg"
  , Tuple "wall-clock" "https://freesound.org/data/previews/188/188615_3330286-lq.mp3"
  -- impros
  , Tuple "impro-glitch" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/improGlitch.ogg"
  , Tuple "impro-wobbly" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/improWobblyGlitch.ogg"
  , Tuple "impro-filigree" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/improFiligree.ogg"
  -- endharm
  , Tuple "andBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andBase0.ogg"
  , Tuple "andIntj0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andIntj0.ogg"
  , Tuple "andIntj1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andIntj1.ogg"
  , Tuple "andIntj2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andIntj2.ogg"
  , Tuple "andThenOneDayBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andThenOneDayBase0.ogg"
  , Tuple "andThenOneDayBase1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andThenOneDayBase1.ogg"
  , Tuple "andThenOneDayIntj0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andThenOneDayIntj0.ogg"
  , Tuple "andThenOneDayIntj1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andThenOneDayIntj1.ogg"
  , Tuple "andThenOneDayIntj2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andThenOneDayIntj2.ogg"
  , Tuple "andThenOneDayIntj3" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andThenOneDayIntj3.ogg"
  , Tuple "andThenOneDayIntj4" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andThenOneDayIntj4.ogg"
  , Tuple "dayBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/dayBase0.ogg"
  , Tuple "finalHe0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/finalHe0.ogg"
  , Tuple "finalHe1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/finalHe1.ogg"
  , Tuple "finalMe" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/finalMe.ogg"
  , Tuple "finalSaid0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/finalSaid0.ogg"
  , Tuple "finalSaid1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/finalSaid1.ogg"
  , Tuple "finalTo0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/finalTo0.ogg"
  , Tuple "finalTo1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/finalTo1.ogg"
  , Tuple "foolsAndKingsBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/foolsAndKingsBase0.ogg"
  , Tuple "foolsAndKingsIntj0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/foolsAndKingsIntj0.ogg"
  , Tuple "foolsAndKingsIntj1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/foolsAndKingsIntj1.ogg"
  , Tuple "heBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/heBase0.ogg"
  , Tuple "magicBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/magicBase0.ogg"
  , Tuple "magicIntj0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/magicIntj0.ogg"
  , Tuple "magicIntj1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/magicIntj1.ogg"
  , Tuple "magicIntj2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/magicIntj2.ogg"
  , Tuple "manyThingsBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/manyThingsBase0.ogg"
  , Tuple "manyThingsBase1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/manyThingsBase1.ogg"
  , Tuple "manyThingsBase2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/manyThingsBase2.ogg"
  , Tuple "manyThingsPedal0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/manyThingsPedal0.ogg"
  , Tuple "manyThingsPedal1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/manyThingsPedal1.ogg"
  , Tuple "manyThingsPedal2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/manyThingsPedal2.ogg"
  , Tuple "ofBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/ofBase0.ogg"
  , Tuple "oneBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/oneBase0.ogg"
  , Tuple "oneBase1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/oneBase1.ogg"
  , Tuple "oneIntj0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/oneIntj0.ogg"
  , Tuple "oneIntj1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/oneIntj1.ogg"
  , Tuple "passedMyBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/passedMyBase0.ogg"
  , Tuple "passedMyBase1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/passedMyBase1.ogg"
  , Tuple "passedMyBase2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/passedMyBase2.ogg"
  , Tuple "passedMyIntj0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/passedMyIntj0.ogg"
  , Tuple "passedMyIntj1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/passedMyIntj1.ogg"
  , Tuple "passedMyIntj2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/passedMyIntj2.ogg"
  , Tuple "passedMyIntj3" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/passedMyIntj3.ogg"
  , Tuple "passedMyIntj4" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/passedMyIntj4.ogg"
  , Tuple "rc0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc0.ogg"
  , Tuple "rc1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc1.ogg"
  , Tuple "rc10" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc10.ogg"
  , Tuple "rc11" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc11.ogg"
  , Tuple "rc12" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc12.ogg"
  , Tuple "rc13" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc13.ogg"
  , Tuple "rc14" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc14.ogg"
  , Tuple "rc15" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc15.ogg"
  , Tuple "rc2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc2.ogg"
  , Tuple "rc3" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc3.ogg"
  , Tuple "rc4" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc4.ogg"
  , Tuple "rc5" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc5.ogg"
  , Tuple "rc6" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc6.ogg"
  , Tuple "rc7" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc7.ogg"
  , Tuple "rc8" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc8.ogg"
  , Tuple "rc9" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/rc9.ogg"
  , Tuple "spokeBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/spokeBase0.ogg"
  , Tuple "thisHeSaidToMeBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/thisHeSaidToMeBase0.ogg"
  , Tuple "thisHeSaidToMeBase1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/thisHeSaidToMeBase1.ogg"
  , Tuple "thisHeSaidToMeBase2" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/thisHeSaidToMeBase2.ogg"
  , Tuple "thisHeSaidToMeBase3" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/thisHeSaidToMeBase3.ogg"
  , Tuple "thisHeSaidToMeBase4" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/thisHeSaidToMeBase4.ogg"
  , Tuple "thisHeSaidToMeBase5" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/thisHeSaidToMeBase5.ogg"
  , Tuple "weBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/weBase0.ogg"
  , Tuple "whileBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/whileBase0.ogg"
  , Tuple "whileWeSpokeOfBase0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/whileWeSpokeOfBase0.ogg"
  , Tuple "whileWeSpokeOfIntj0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/whileWeSpokeOfIntj0.ogg"
  , Tuple "whileWeSpokeOfIntj1" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/whileWeSpokeOfIntj1.ogg"
  , Tuple "whileWeSpokeOfPedal0" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/whileWeSpokeOfPedal0.ogg"
  , Tuple "andBeBuzzheng" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andBeBuzzheng.ogg"
  -- endgame
  , Tuple "andBeFlange" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andBeFlange.ogg"
  , Tuple "andBeLovedInRe" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andBeLovedInRe.ogg"
  , Tuple "andBeNylon" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andBeNylon.ogg"
  , Tuple "andBeShamisen" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/andBeShamisen.ogg"
  , Tuple "isJustToBuzzheng" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/isJustToBuzzheng.ogg"
  , Tuple "isJustToFlange" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/isJustToFlange.ogg"
  , Tuple "isJustToLove" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/isJustToLove.ogg"
  , Tuple "isJustToNylon" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/isJustToNylon.ogg"
  , Tuple "isJustToShamisen" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/isJustToShamisen.ogg"
  , Tuple "theGreatestBuzzheng" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/theGreatestBuzzheng.ogg"
  , Tuple "theGreatestFlange" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/theGreatestFlange.ogg"
  , Tuple "theGreatestNylon" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/theGreatestNylon.ogg"
  , Tuple "theGreatestShamisen" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/theGreatestShamisen.ogg"
  , Tuple "theGreatestThing" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/theGreatestThing.ogg"
  , Tuple "turn" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/turn.ogg"
  , Tuple "turnBuzzheng" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/turnBuzzheng.ogg"
  , Tuple "turnFlange" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/turnFlange.ogg"
  , Tuple "turnNylon" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/turnNylon.ogg"
  , Tuple "youllEverBuzzheng" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/youllEverBuzzheng.ogg"
  , Tuple "youllEverFlange" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/youllEverFlange.ogg"
  , Tuple "youllEverLearn" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/youllEverLearn.ogg"
  , Tuple "youllEverNylon" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/youllEverNylon.ogg"
  , Tuple "youllEverShamisen" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/youllEverShamisen.ogg"
  , Tuple "shaker" "https://klank-share.s3-eu-west-1.amazonaws.com/nature-boy/eggshaker.mp3"
  ]
